# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fce7ad2432abda3fa3b0975ab4f700aae63b3c3305c3d504350be6299fc77361e888e302f1af9fc3a81052e562ddd7c076a3e1eff8c69b5b5dd5694957010092

test:
  secret_key_base: 0297535f80e6533f4c6fdccfee23cbe275004ab1e5f8ab2d14143ccf108a1d837cc7e597302260fc19e017542ce58a48dc9af83af661590e9901a40a6ecc3a06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
